### ISSUE TITLE
Google nexus 7 is identified as phone

### ISSUE THREAD

**Issue by shadowed87** [fnando/browser#147]
Tested in google chrome "inspect element" with device selected nexus 7, it gets identified as phone

**Comment by fnando** [comment]
You mean you selected the user agent Nexus 7 under Chrome's Web Developers tools? If so, it's detected as mobile because it advertises as so. [Here's the user agent](http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Linux%3B+Android+4.3%3B+Nexus+7+Build%2FJSS15Q%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F42.0.2307.2+Mobile+Safari%2F537.36&accept_language=en-US%2Cen%3Bq%3D0.8%2Cpt%3Bq%3D0.6).

**Comment by fnando** [comment]
Closing since there's was no feedback.
