### ISSUE TITLE
Detecting Android versions same as iOS

### ISSUE THREAD

**Issue by TheSmartnik** [fnando/browser#178]
Hi, I'm thinking something like `android2?` might be a useful improvement. What do you say?

**Comment by fnando** [comment]
I'm planning to refactor these numbered methods to be something more manageable. Instead of adding `ios5?`, `ios6?`, and so on, we would have just `ios?`, which can optionally receive the version you want to detect, e.g. `ios?(9)`.

That said, yeah, go ahead and implement these numbered methods for now. Remember to write tests for it and update the README. ;)

**Comment by TheSmartnik** [comment]
:+1:
