### ISSUE TITLE
browser.device.mobile? returns nil

### ISSUE THREAD

**Issue by chrishough** [fnando/browser#294]
When attempting to implement https://github.com/fnando/browser/issues/136 today we noticed that the mobile function returns a nil instead of a true or false. I would consider this a bug.

<img width="710" alt="screen shot 2017-03-28 at 8 26 57 am" src="https://cloud.githubusercontent.com/assets/744056/24413481/64daddba-1390-11e7-9598-6268758a8553.png">

```ruby
module BrowserHelper
  def desktop_browser?
    !(browser.device.mobile? && browser.device.tablet?)
  end
end
```

**Comment by fnando** [comment]
This is not a bug. Predicate methods returning `nil` values were mentioned before (like #245). Ruby doesn't really have an opinion on this. The community does.

Since `nil` is a falsy value just like false itself, I don't think we should coerce values. Just don't type check on your end and you should be fine. If you do need boolean values, you can always `!!value` on your side too.

**Comment by chrishough** [comment]
I tend to follow ruby community guidelines which you are correct, methods with `?` return true or false.  I will adjust the code on my side.
