### ISSUE TITLE
browser.mobile? returns an empty result 

### ISSUE THREAD

**Issue by medBouzid** [fnando/browser#321]
Why browser.mobile? does not return anything while browser.tablet? returns false  !!!??

**Comment by fnando** [comment]
By empty result I assume you mean `nil`. If that's the case, that's the expected result. I answered this before, but here it is:

Traditionally, predicate methods are recommended to return booleans, althought that's not a rule set in stone. See Ruby's own `Numeric#nonzero?`.

```ruby
5.1.4@2.4.2 (main)> 0.nonzero?
=> nil
5.1.4@2.4.2 (main)> 1.nonzero?
=> 1
```

This is exactly the case with this lib; we're returning a `falsy` value, not `false` itself.

**Comment by medBouzid** [comment]
@fnando thank you for the explanation, but it's just confusing to see browser.tablet? returning "false" and not "nil" !!!

**Comment by gsheppard** [comment]
To anyone coming to this down the road: I also agree that the `true`/`nil` return values are confusing since unlike `.nonzero?`, there's no functional purpose to the nil return (technically that method returns self or nil for chaining purposes and avoids booleans altogether).

However...

This conversation (https://github.com/rails/rails/issues/20110) kinda got me on the same page in terms of not littering the code with a ton of `!!`. Especially in a library like _browser_ which is almost exclusively predicates, having every other line wrapped in `!!()` would start to get ugly.

**Comment by marktellez** [comment]
It might not be a rule set in stone, but it has been a ruby practice as long as I have been coding ruby (2006). Putting forth an obscure exception to the rule rather than the large amount of examples of rule that go against you is also bad logic and not user friendly.

**Comment by fnando** [comment]
@marktellez Yeah, I had this conversation before, and I understand that it may get confusing if you **type check** your code. Why would you check for `nil`, if is a falsy value? `browser.device.mobile? "mobile" : "non-mobile"` is enough. If you need boolean because you want to store it on your database, do a `!!browser.device.mobile?`.

**Comment by fnando** [comment]
Also, the [comment above yours](https://github.com/fnando/browser/issues/321#issuecomment-339362423) summarizes my reasoning perfectly.
