### ISSUE TITLE
Google Mobile Friendly Test Issue

### ISSUE THREAD

**Issue by cemalivive** [fnando/browser#372]
Hello,

My website works very well. I never had a problem with this. But when I run a test on this Google tool(https://search.google.com/test/mobile-friendly), it performs the test on my desktop website and therefore I get a wrong result.
How to fix that? Any idea?

**Comment by gchiaren** [comment]
+1 I have intermittent issues with the Google mobile-friendly test as well, and I use this gem to detect a mobile user agent.

**Comment by fnando** [comment]
Looks like it uses this user agent: `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`.

What should be the expected behaviour as far as detection goes? It looks fine, by the output below:

```irb
> browser = Browser.new 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
> browser.bot?
=> true
> browser.name
=> "Chrome"
> browser.device.mobile?
=> true
```
