### ISSUE TITLE
Supported Ruby versions?

### ISSUE THREAD

**Issue by aried3r** [fnando/browser#417]
Which Ruby versions are officially supported by this gem? Going by the `.travis.yml` file, Ruby 2.4 support (testing) was "dropped"(?) in this commit https://github.com/fnando/browser/commit/c9a47545deb8c3ea4856ae74f8439e2cb35b4fe0. I was wondering, because the [`.gemspec` file says >= 2.0](https://github.com/fnando/browser/blob/e7ddbd3fe28537a50fe547105da9e385177184e9/browser.gemspec#L4) while the CHANGELOG.md says that [version 2.4.0](https://github.com/fnando/browser/blob/master/CHANGELOG.md#v240) of this gem removed Ruby 2.1 support, which was released in [May 2017](https://github.com/fnando/browser/releases/tag/v2.4.0).

**Comment by fnando** [comment]
Officially, I support the latest two Ruby versions on all of my projects, unless specified otherwise on `.travis.yml`. I don't lock the version on the gemspec though; maybe it'll work, maybe it won't. The current restriction was back in the day when Ruby 1.9 had different feature set than 2.0 and can be removed.

**Comment by aried3r** [comment]
Thank you for the quick response!
