### ISSUE TITLE
NoMethodError: undefined method `match?' for #<String:0x00000001c9e388>

### ISSUE THREAD

**Issue by rppandi** [fnando/browser#509]
## Description
Browser gem not working

NoMethodError: undefined method `match?' for #<String:0x00000001c9e388>
## How to reproduce

string = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36"
 => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36" 
2.3.0 :007 > browser = Browser.new(string, accept_language:"en-us")

## Software:

- Rails version: rails 4.2.11 & ruby 2.3.0
- Browser gem version: browser (5.2.0)

## Full backtrace

```text
2.3.0 :006 > string = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36"
 => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36" 
2.3.0 :007 > browser = Browser.new(string, accept_language:"en-us")
NoMethodError: undefined method `match?' for #<String:0x00000001c9e388>
Did you mean?  match
	from /home/palpandi/.rvm/gems/ruby-2.3.0/gems/browser-5.2.0/lib/browser/blackberry.rb:20:in `match?'
	from /home/palpandi/.rvm/gems/ruby-2.3.0/gems/browser-5.2.0/lib/browser/browser.rb:106:in `each'
	from /home/palpandi/.rvm/gems/ruby-2.3.0/gems/browser-5.2.0/lib/browser/browser.rb:106:in `find'
	from /home/palpandi/.rvm/gems/ruby-2.3.0/gems/browser-5.2.0/lib/browser/browser.rb:106:in `new'
	from (irb):7
	from /home/palpandi/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'

```

**Comment by fnando** [comment]
Turns out ruby-2.3 doesn't have `String#match?`. Given that this ruby version is EOL-ed, my suggestion would be adding the following core extension to your application (possibly `config/initializers/string_ext.rb`, given that you're using Rails). It's not a 1-1 implementation, but it'll do the job. Alternatively, you could use an older version.

```
class String
  def match?(pattern)
    pattern = Regexp.new(Regexp.escape(pattern)) unless pattern.is_a?(Regexp)
    !!(self =~ pattern)
  end
end
```

That said, I'm going to bump up the minimum Ruby requirement to 2.4.0, which introduces `String#match?`.
